apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-backend
  namespace: taskmanager
  labels:
    app: taskmanager-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager-backend
  template:
    metadata:
      labels:
        app: taskmanager-backend
    spec:
      containers:
        - name: backend
          image: DOCKERHUB_USERNAME/taskmanager-backend:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: NODE_ENV
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: CLOUD_NAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: API_SECRET
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
